name: PR Merged test

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

permissions:
  pull-requests: read
  checks: write
  actions: write

jobs:
  pr_merge_label:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check PR labels - nestjs
        id: pr-labels-nestjs
        uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: nestjs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          allowFailure: true

      - name: Check PR labels - spring
        id: pr-labels-spring
        uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: spring
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          allowFailure: true

      - name: nestjs label cicd
        if: steps.pr-labels-nestjs.outputs.passed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/nestjs-cicd.yml/dispatches \
          -d '{"ref":"heads/dev"}'

      - name: spring label cicd
        if: steps.pr-labels-spring.outputs.passed == 'true'
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/spring-cicd.yml/dispatches \
          -d '{"ref":"heads/dev"}'
