name: PR Merged test

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

permissions:
  pull-requests: read
  checks: write

jobs:
  pr_merge_label:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "merged True"

      - name: Check PR labels - nestjs
        id: pr-labels-nestjs
        uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: nestjs
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Check PR labels - spring
        id: pr-labels-spring
        uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: spring
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Run actions based on nestjs label
        if: steps.pr-labels-nestjs.outputs.passed == true
        run: echo "nestjs"

      - name: Run actions based on spring label
        if: steps.pr-labels-spring.outputs.passed == true
        run: echo "spring"
