name: PR Merged test

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

permissions:
  pull-requests: read
  checks: write
  actions: write

jobs:
  pr_merge_label:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      nestjs_label: ${{ steps.pr-labels-nestjs.outputs.passed }}
      spring_label: ${{ steps.pr-labels-spring.outputs.passed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check PR labels - nestjs
        id: pr-labels-nestjs
        uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: nestjs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          allowFailure: true

      - name: Check PR labels - spring
        id: pr-labels-spring
        uses: danielchabr/pr-labels-checker@v3.3
        with:
          hasSome: spring
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          allowFailure: true

      - name: Set outputs
        run: |
          echo "nestjs_label=${{ steps.pr-labels-nestjs.outputs.passed }}" >> $GITHUB_ENV
          echo "spring_label=${{ steps.pr-labels-spring.outputs.passed }}" >> $GITHUB_ENV
