name: NestJS CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nest-docker-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/gotiger/site/nest-test

            # Docker Hub 로그인
            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

            # 이미지 풀링
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nest-docker-test:latest

            # 새로운 이미지를 Green/Blue 중 하나로 태그
            if docker ps | grep app_blue; then
              NEW_DEPLOYMENT="green"
              OLD_DEPLOYMENT="blue"
            else
              NEW_DEPLOYMENT="blue"
              OLD_DEPLOYMENT="green"
            fi

            docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/nest-docker-test:latest ${{ secrets.DOCKER_HUB_USERNAME }}/nest-docker-test:$NEW_DEPLOYMENT
            docker-compose up -d app_$NEW_DEPLOYMENT

            sleep 10 # 새 컨테이너가 시작될 시간을 기다림

            # Nginx 설정 변경
            if [ "$NEW_DEPLOYMENT" == "green" ]; then
              sed -i "s/proxy_pass http:\/\/app_$OLD_DEPLOYMENT:3000;/proxy_pass http:\/\/app_$NEW_DEPLOYMENT:3000;/" /home/gotiger/nginx/conf.d/nest-test.conf
            else
              sed -i "s/proxy_pass http:\/\/app_$OLD_DEPLOYMENT:3000;/proxy_pass http:\/\/app_$NEW_DEPLOYMENT:3000;/" /home/gotiger/nginx/conf.d/nest-test.conf
            fi

            # Nginx 재시작
            docker-compose -f /home/gotiger/docker-compose-multi.yml up -d --force-recreate --no-deps nginx

            # 이전 버전의 컨테이너 중지 및 제거
            docker-compose stop app_$OLD_DEPLOYMENT
            docker-compose rm -f app_$OLD_DEPLOYMENT
